### ISSUE TITLE
图片超过宽度,css应该限制

### ISSUE THREAD

**Issue by xiamuguizhi** [smallyunet/hexo-theme-yinwang#1]
[![TIM截图20190506105625.png](https://i.loli.net/2019/05/06/5ccfa2a6b88c2.png)](https://i.loli.net/2019/05/06/5ccfa2a6b88c2.png)

img{display: block;max-width: 100%;}

自行解决了，我都是大图 /(ㄒoㄒ)/~~

**Comment by smallyunet** [comment]
@xiamuguizhi 
抱歉回复不及时，非常感谢您的反馈，已在 850444ef93284ab11f52060960c0f137786f219a 中添加代码
