### ISSUE TITLE
样式问题

### ISSUE THREAD

**Issue by djansun** [smallyunet/hexo-theme-yinwang#11]
点击“博客菜单”后会在新标签页打开博客，希望在原标签页下返回该怎样做？

![image](https://user-images.githubusercontent.com/89949960/138857041-5ff8c768-429d-4483-a52a-f7ddea818958.png)

**Comment by xiamuguizhi** [comment]
找到 `target="_bank"` 把他去掉就行。

**Comment by djansun** [comment]
主题下的config文件没有这一项，那应该自己建么？

**Comment by xiamuguizhi** [comment]
@djansun 好的  我太久没用这个程序了 我以为在主题文件改的  忘记设置也可以了。

**Comment by djansun** [comment]
已解决，感谢！
![image](https://user-images.githubusercontent.com/89949960/138859694-5265e70f-0fb2-4c91-b866-31b60327f4d7.png)
