### ISSUE TITLE
tags page Error message

### ISSUE THREAD

**Issue by SugarCreate** [smallyunet/hexo-theme-yinwang#15]
/hexo-theme-yinwang/layout/tag.pug:5
    3|   .inner
    4|     h3= page.tag
  > 5|     if page.posts.length > 0
    6|     ul.list-group
    7|       each post in page.posts.sort('date', -1).toArray()
    8|         li.list-group-item.title

Cannot read property 'length' of undefined

**Comment by smallyunet** [comment]
I think you use the old code version.

By the way, you should add the `type: tags` in the `source/tags/index.md` file to use the tags pages.

It's my mistake and I add some description in README. e9c732e9470fae1fdf495698ad453f673d1a503e

**Comment by SugarCreate** [comment]
I will try again.
Thx,

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年8月30日 18:32
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [smallyunet/hexo-theme-yinwang] tags page Error message (Issue #15)


I think you use the old code version.

By the way, you should add the type: tags in the source/tags/index.md file to use the tags pages.

It's my mistake and I add some description in README. e9c732e<https://github.com/smallyunet/hexo-theme-yinwang/commit/e9c732e9470fae1fdf495698ad453f673d1a503e>

―
