### ISSUE TITLE
文章目录添加

### ISSUE THREAD

**Issue by toleleYJL** [smallyunet/hexo-theme-yinwang#16]
小白问一下，该怎么制作并添加文章的目录呢？

**Comment by smallyunet** [comment]
文章的目录是啥意思，能具体描述下吗 @toleleYJL

**Comment by toleleYJL** [comment]
就像这样。我目前用html的标签简单实现了一下，后期我再自行学习其它实现方法。
![image](https://user-images.githubusercontent.com/114792220/202892986-22835e55-9894-4186-93ea-c7d8415bbc91.png)
@smallyunet

**Comment by smallyunet** [comment]
如果是 hexo 主题，可以用这个 toc 函数：https://hexo.io/docs/helpers.html#toc

需要编辑主题的文件，比如在 `themes/hexo-theme-yinwang/layout/post.pug` 文件加上这行：

```
!= toc(page.content)
```

**Comment by toleleYJL** [comment]
哇~   竟然可以自动生成！十分感谢（抱拳）
