### ISSUE TITLE
没有出现主题样式

### ISSUE THREAD

**Issue by xie-yuping** [smallyunet/hexo-theme-yinwang#18]
![9I6JPAP)V0ZMM_ U(R0BTPR](https://user-images.githubusercontent.com/100059974/225325729-4266436a-a903-4a3f-a04f-7ed497fefd4b.png)
你好！我按照 demo 仓库的操作后，出现了这种情况，请问该如何回答呢？盼回复，谢谢！

**Comment by xie-yuping** [comment]
![%L}`(EC$_1T%M@T A3{H1K3](https://user-images.githubusercontent.com/100059974/225326894-76791d99-8037-4b29-a700-d5776dc2cfa9.png)
检查了 packpage 包，并且 运行了 renderer 的命令

**Comment by xie-yuping** [comment]
![G@`XQXZ7J~595_9BMMCYXAM](https://user-images.githubusercontent.com/100059974/225534959-862faa89-aa90-4a1c-9057-513be3744a6e.png)
请问这种情况该怎么处理呢？

**Comment by smallyunet** [comment]
我看到第一个图显示的是 github 的网址。把仓库的 pages 设置为 docs 作为网站目录了吗？
<img width="1022" alt="Screenshot 2023-03-16 at 16 06 47" src="https://user-images.githubusercontent.com/20765689/225553499-ad356e61-6d7e-4ae1-9281-a90b02039c4f.png">

**Comment by xie-yuping** [comment]
我没有对pages进行操作。

我重新按步骤重试了一遍，先搭建hexo框架，再加上主题。尝试没有把 ture 改为 false，最后上线成功了。总之，非常感谢你 :)
![3EMS})P)NC) H`R12(G SDX](https://user-images.githubusercontent.com/100059974/225800166-943e2756-4e55-40eb-a74f-05d39ea69711.png)
