### ISSUE TITLE
导航栏的问题

### ISSUE THREAD

**Issue by xie-yuping** [smallyunet/hexo-theme-yinwang#19]
![FK%_AKW6M6{P NQ@UZ(O(0K](https://github.com/smallyunet/hexo-theme-yinwang/assets/100059974/76710593-05bd-4f6b-8857-5788fbc595ba)
①导航栏的按钮可以直接跳转到指定网页吗？能的话，该到哪里修改呢？
②可以删除一些按钮吗？在哪里删除呢？
希望得到得到解答，谢谢

**Comment by smallyunet** [comment]
在主题的配置文件 _config.yml 里：https://github.com/smallyunet/hexo-theme-yinwang/blob/master/_config.yml

**Comment by xie-yuping** [comment]
![J$S 1KDO(V}NXL7}JR3Y(YP](https://github.com/smallyunet/hexo-theme-yinwang/assets/100059974/0039e755-57a8-49a8-b416-4bd0fe1670ac)
好的。我把网址输入后，点击对应的按钮，出现了如下情况，请问是什么原因呢？
![A1 _$61J5{M2YPUFR8{Z P3](https://github.com/smallyunet/hexo-theme-yinwang/assets/100059974/7a5cd2ec-b12e-4050-abeb-12332e467302)

**Comment by xie-yuping** [comment]
![4V6C~7R$UL_ %FQ B}(6JH](https://github.com/smallyunet/hexo-theme-yinwang/assets/100059974/0854d8d6-7086-406e-89fd-71f64ca8c41a)
这是修改后的按钮，显示的信息。该怎么去掉前面带的博客地址呢？

**Comment by smallyunet** [comment]
确实有问题

**Comment by smallyunet** [comment]
fixed in  https://github.com/smallyunet/hexo-theme-yinwang/commit/f460fe19bb920459cd303f4001538a97ccca4ce7
