### ISSUE TITLE
作者，考虑支持一下上下标吗.

### ISSUE THREAD

**Issue by jauzzz** [smallyunet/hexo-theme-yinwang#2]
编辑器里
![image](https://user-images.githubusercontent.com/17628634/63578955-26662100-c5c4-11e9-859a-07274a4df486.png)

页面上
![image](https://user-images.githubusercontent.com/17628634/63578983-32ea7980-c5c4-11e9-9867-5b0bde53f5c5.png)

**Comment by smallyunet** [comment]
@jauzzz 
你好，这也许是MarkDown语法差异带来的问题，请尝试使用这样的方式来表示上下标：

```
// 下标
H<sub>2</sub>O
// 上标
x<sup>2</sup>
```

这是页面上的效果：
![搜狗截图20190824113237](https://user-images.githubusercontent.com/20765689/63632091-e4d88300-c662-11e9-8380-c678ff1dc1db.png)

**Comment by jauzzz** [comment]
噢噢，确实如此！感谢.

**Comment by jauzzz** [comment]
我看最新commit提交了tag cloud的功能，更新之后导航栏出现了标签云，点击报错 `Cannot GET /tags/`，请问有更具体的食用方式吗

**Comment by smallyunet** [comment]
@jauzzz 
抱歉这是我的失误，我不该把它放在默认配置里。

要使用的话，可以先new一个页面：
```
hexo new page tags
```
然后把页面type设置为tags，也就是修改`source/tags/index.md`，修改之后看起来是这样：
```
---
title: 标签云
date: 2019-08-24 22:00:47
type: tags
---
```
应该就可以访问了：http://localhost:4000/tags

当然，要保证依赖中安装了`hexo-generator-tag`，查看`package.json`如果依赖中没有这一项，可以运行命令安装它：
```
npm install hexo-generator-tag --save
```

**Comment by jauzzz** [comment]
吃上了！感谢作者！！！
