### ISSUE TITLE
文章样式问题

### ISSUE THREAD

**Issue by Gee233** [smallyunet/hexo-theme-yinwang#7]
为啥您博客代码块那么好看，我用了您的主题，但是同样的markdown语法写出来的样式布局非常乱，请问需要改哪里吗？

**Comment by smallyunet** [comment]
你好，非常抱歉没有及时回复您，我没有经常关注这里的 issue。您可以直接使用 [hexo-blog](https://github.com/smallyunet/hexo-blog) 仓库中包含的主题。这个仓库中的主题版本没有及时更新。
