### ISSUE TITLE
主题引入失败

### ISSUE THREAD

**Issue by anghunk** [smallyunet/hexo-theme-yinwang#8]
[DEMO图片](https://vkceyugu.cdn.bspapp.com/VKCEYUGU-imgbed/0924be57-c330-4b84-86cd-55bb88c06228.png)

**Comment by smallyunet** [comment]
你好，请确认 package.json 中包含 `hexo-renderer-pug` 依赖。其他依赖项可以参考 [package.json](https://github.com/smallyunet/hexo-blog/blob/master/package.json)。

或者直接执行以下命令后重试：

```
npm install hexo-renderer-pug --save
```
